/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedJobsBrowseRouteImport } from './routes/_authenticated/jobs-browse'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicantsRouteImport } from './routes/_authenticated/applicants'
import { Route as AuthenticatedMyApplicationsIndexRouteImport } from './routes/_authenticated/my-applications.index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies.index'
import { Route as AuthenticatedMyApplicationsIdRouteImport } from './routes/_authenticated/my-applications.$id'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated/companies.$id'
import { Route as AuthenticatedJobsIdPipelineRouteImport } from './routes/_authenticated/jobs.$id.pipeline'
import { Route as AuthenticatedJobsIdApplicantsRouteImport } from './routes/_authenticated/jobs.$id.applicants'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsBrowseRoute = AuthenticatedJobsBrowseRouteImport.update({
  id: '/jobs-browse',
  path: '/jobs-browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicantsRoute = AuthenticatedApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyApplicationsIndexRoute =
  AuthenticatedMyApplicationsIndexRouteImport.update({
    id: '/my-applications/',
    path: '/my-applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyApplicationsIdRoute =
  AuthenticatedMyApplicationsIdRouteImport.update({
    id: '/my-applications/$id',
    path: '/my-applications/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsIdPipelineRoute =
  AuthenticatedJobsIdPipelineRouteImport.update({
    id: '/jobs/$id/pipeline',
    path: '/jobs/$id/pipeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsIdApplicantsRoute =
  AuthenticatedJobsIdApplicantsRouteImport.update({
    id: '/jobs/$id/applicants',
    path: '/jobs/$id/applicants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applicants': typeof AuthenticatedApplicantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs-browse': typeof AuthenticatedJobsBrowseRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/my-applications/$id': typeof AuthenticatedMyApplicationsIdRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/my-applications/': typeof AuthenticatedMyApplicationsIndexRoute
  '/jobs/$id/applicants': typeof AuthenticatedJobsIdApplicantsRoute
  '/jobs/$id/pipeline': typeof AuthenticatedJobsIdPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applicants': typeof AuthenticatedApplicantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs-browse': typeof AuthenticatedJobsBrowseRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/my-applications/$id': typeof AuthenticatedMyApplicationsIdRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/my-applications': typeof AuthenticatedMyApplicationsIndexRoute
  '/jobs/$id/applicants': typeof AuthenticatedJobsIdApplicantsRoute
  '/jobs/$id/pipeline': typeof AuthenticatedJobsIdPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/applicants': typeof AuthenticatedApplicantsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs-browse': typeof AuthenticatedJobsBrowseRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/my-applications/$id': typeof AuthenticatedMyApplicationsIdRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/my-applications/': typeof AuthenticatedMyApplicationsIndexRoute
  '/_authenticated/jobs/$id/applicants': typeof AuthenticatedJobsIdApplicantsRoute
  '/_authenticated/jobs/$id/pipeline': typeof AuthenticatedJobsIdPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/applicants'
    | '/dashboard'
    | '/jobs-browse'
    | '/pipeline'
    | '/companies/$id'
    | '/my-applications/$id'
    | '/companies/'
    | '/jobs/'
    | '/my-applications/'
    | '/jobs/$id/applicants'
    | '/jobs/$id/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/applicants'
    | '/dashboard'
    | '/jobs-browse'
    | '/pipeline'
    | '/companies/$id'
    | '/my-applications/$id'
    | '/companies'
    | '/jobs'
    | '/my-applications'
    | '/jobs/$id/applicants'
    | '/jobs/$id/pipeline'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/applicants'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs-browse'
    | '/_authenticated/pipeline'
    | '/_authenticated/companies/$id'
    | '/_authenticated/my-applications/$id'
    | '/_authenticated/companies/'
    | '/_authenticated/jobs/'
    | '/_authenticated/my-applications/'
    | '/_authenticated/jobs/$id/applicants'
    | '/_authenticated/jobs/$id/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs-browse': {
      id: '/_authenticated/jobs-browse'
      path: '/jobs-browse'
      fullPath: '/jobs-browse'
      preLoaderRoute: typeof AuthenticatedJobsBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applicants': {
      id: '/_authenticated/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof AuthenticatedApplicantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-applications/': {
      id: '/_authenticated/my-applications/'
      path: '/my-applications'
      fullPath: '/my-applications/'
      preLoaderRoute: typeof AuthenticatedMyApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-applications/$id': {
      id: '/_authenticated/my-applications/$id'
      path: '/my-applications/$id'
      fullPath: '/my-applications/$id'
      preLoaderRoute: typeof AuthenticatedMyApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$id/pipeline': {
      id: '/_authenticated/jobs/$id/pipeline'
      path: '/jobs/$id/pipeline'
      fullPath: '/jobs/$id/pipeline'
      preLoaderRoute: typeof AuthenticatedJobsIdPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$id/applicants': {
      id: '/_authenticated/jobs/$id/applicants'
      path: '/jobs/$id/applicants'
      fullPath: '/jobs/$id/applicants'
      preLoaderRoute: typeof AuthenticatedJobsIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApplicantsRoute: typeof AuthenticatedApplicantsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsBrowseRoute: typeof AuthenticatedJobsBrowseRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedMyApplicationsIdRoute: typeof AuthenticatedMyApplicationsIdRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedMyApplicationsIndexRoute: typeof AuthenticatedMyApplicationsIndexRoute
  AuthenticatedJobsIdApplicantsRoute: typeof AuthenticatedJobsIdApplicantsRoute
  AuthenticatedJobsIdPipelineRoute: typeof AuthenticatedJobsIdPipelineRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicantsRoute: AuthenticatedApplicantsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsBrowseRoute: AuthenticatedJobsBrowseRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
  AuthenticatedMyApplicationsIdRoute: AuthenticatedMyApplicationsIdRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedMyApplicationsIndexRoute: AuthenticatedMyApplicationsIndexRoute,
  AuthenticatedJobsIdApplicantsRoute: AuthenticatedJobsIdApplicantsRoute,
  AuthenticatedJobsIdPipelineRoute: AuthenticatedJobsIdPipelineRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
